//EMAIL
const MAX_LENGHT_EMAIL = 40
const MIN_LENGHT_EMAIL = 6

//NAME
const MAX_LENGHT_NAME = 40
const MIN_LENGHT_NAME = 5

//PAGINATION DEFAULT CONSTANTS
const DEFAULT_PAGE_NUMBER = 1
const DEFAULT_LIMIT = 5
const MIN_LIMIT = 1
const MAX_LIMIT = 10


module.exports = {  MAX_LENGHT_EMAIL, MIN_LENGHT_EMAIL, 
                    MAX_LENGHT_NAME, MIN_LENGHT_NAME,
                    DEFAULT_PAGE_NUMBER, DEFAULT_LIMIT, MAX_LIMIT, MIN_LIMIT}